# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='dateTimeField',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 2, 29, 51, 9313, tzinfo=utc)),
        ),
    ]
