# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0002_auto_20160306_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='dateTimeField',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 3, 50, 2, 546482, tzinfo=utc)),
        ),
    ]
